on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Build macism
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          swiftc macism.swift -o macism

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            macism
          tag_name: latest
